name: Python Build and Run

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build
        run: python -m py_compile app.py

      - name: Run
        run: python app.py